# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

# @url = http://localhost:5001/fire-next-6ce5d/us-central1/logSensorData
@url = https://logsensordata-mo6xjx5ntq-uc.a.run.app

POST {{url}}
Content-Type: application/json

{
  "deviceId": "pd5qBQOHtbDHSkvlnTFA",
  "temperature": 25.5,
  "humidity": 60,
  "battery": 85
}